# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observations',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Guide'),
        ),
        migrations.AddField(
            model_name='observations',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observations',
            name='user_modified',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifest',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifest',
            name='user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Manifest'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guide_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Zone'),
        ),
    ]
