# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=100, verbose_name='nombres/razon social')),
                ('number_doc', models.CharField(max_length=100, verbose_name='dni/ruc')),
                ('address', models.CharField(max_length=100, verbose_name='direccion')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='telefono')),
                ('mobil', models.CharField(blank=True, max_length=15, verbose_name='celular')),
                ('web', models.URLField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='cliente')),
                ('type_clint', models.CharField(choices=[('0', 'Juridica'), ('1', 'Natural')], max_length=2, verbose_name='Tipo de Cliente')),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=40, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=40, verbose_name='apellidos')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='telefono/celular')),
                ('address', models.CharField(max_length=100, verbose_name='direccion')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1, verbose_name='sexo')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='driver')),
                ('license', models.CharField(blank=True, max_length=11, verbose_name='licencia')),
                ('class_driver', models.CharField(blank=True, max_length=2, verbose_name='Clase de licencia')),
                ('category', models.CharField(blank=True, max_length=2)),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=40, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=40, verbose_name='apellidos')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='telefono/celular')),
                ('address', models.CharField(max_length=100, verbose_name='direccion')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1, verbose_name='sexo')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee')),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
