# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Salida')),
                ('date_retunr', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Retorno')),
                ('state', models.CharField(choices=[('0', 'Asignado'), ('1', 'Salio'), ('2', 'Volvio')], max_length=2, verbose_name='Estado Asignacion')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_asignation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('model', models.CharField(max_length=30, verbose_name='Modelo de Vehiculo')),
                ('plaque', models.CharField(max_length=7, verbose_name='Placa')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefono Asignado')),
                ('code_settings_car', models.CharField(max_length=6, verbose_name='codigo de configuracion vehicular')),
                ('constancy_inscription', models.CharField(max_length=12, verbose_name='Constancia de Inscripcion')),
                ('state', models.BooleanField(default=False, verbose_name='Estado')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_user_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailAsignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('asignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.Asignation')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asignation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.Car'),
        ),
        migrations.AddField(
            model_name='asignation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_user_asignation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignation',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignation',
            name='user_modified',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignation_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
