# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailasignation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepcion.Guide'),
        ),
    ]
