# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignacion', '0002_detailasignation_guide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='user_modified',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_user_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignation',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_asignation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion.Car'),
        ),
        migrations.AddField(
            model_name='asignation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_user_asignation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignation',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignation',
            name='user_modified',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignation_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
